apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: theshoeshop-microservices-backend
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/GayanKod/TheShoeShop-microservices_backend
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/manifests/

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: theshoeshop-microservices-backend
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: theshoeshop-microservices-backend
  targetNamespace: default