apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'product_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['product-service.default.svc.cluster.local']
            labels:
              application: 'Product Service Application'
      - job_name: 'order_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['order-service.default.svc.cluster.local']
            labels:
              application: 'Order Service Application'
      - job_name: 'inventory_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['inventory-service.default.svc.cluster.local']
            labels:
              application: 'Inventory Service Application'
      - job_name: 'notification_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['notification-service.default.svc.cluster.local']
            labels:
              application: 'Notification Service Application'