apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.metadata.labels.app}}
  name: {{ .Values.metadata.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app}}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app}}
    spec:
      containers:
        - env:
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: ' TRACE'
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: "{{ .Values.container.image}}:{{ .Values.container.tag}}"
          name: {{ .Values.container.name}}
          ports:
            - containerPort: {{ .Values.container.port}}
            - containerPort: {{ .Values.container.targetPort}}
          resources: {}
      restartPolicy: Always
status: {}