apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.metadata.labels.app}}
  name: {{ .Values.metadata.name}}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.metadata.labels.app}}
status:
  loadBalancer: {}