# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: {{ .Values.metadata.labels.app }}
#   name: {{ .Values.metadata.name}}
# spec:
#   ports:
#     - name: "8761"
#       port: {{ .Values.container.port}}
#       targetPort: {{ .Values.container.port}}
#   selector:
#     app: {{ .Values.metadata.labels.app }}
# status:
#   loadBalancer: {}

apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka
  selector:
    app: eureka

---                  

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761