apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: F:\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    app: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}
spec:
  ports:
    - name: "9092"
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.metadata.labels.app }}
status:
  loadBalancer: {}