apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.metadata.labels.app}}
  name: {{ .Values.metadata.name}}
spec:
  ports:
    - name: "5432"
      port: {{ .Values.container.port}}
      targetPort: {{ .Values.container.port}}
  selector:
    app:  {{ .Values.metadata.labels.app}}
status:
  loadBalancer: {}