apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.metadata.labels.app}}
  name: {{ .Values.metadata.name}}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app}}
  strategy: {}
  template:
    metadata:

      labels:
        app: {{ .Values.metadata.labels.app}}
    spec:
      containers:
        - image: {{ .Values.container.image }}
          name: {{ .Values.container.name }}
          ports:
            - containerPort: {{ .Values.container.port }}
          resources: {}
      restartPolicy: Always
status: {}