apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name}}
  labels:
    app: {{ .Values.metadata.labels.app}}
spec:
  selector:
    app: {{ .Values.metadata.labels.app}}
  ports:
    - port: {{ .Values.container.port}}
      targetPort: {{ .Values.container.port}}
status:
  loadBalancer: {}